### ISSUE TITLE
The package can't be installed under win/osx

### ISSUE THREAD

**Issue by Ryukaj95** [comelz/quark#12]
As the title, the package can't be installed in windows/osx machines.
I've tried two ways to install them for both the environments:

```python3 -m pip install https://github.com/comelz/quark.git```
```
git clone https://github.com/comelz/quark.git
cd quark
python3 -m setup.py install
```

For both, when I tried to call `quark`, the console raised an _command not found_ error.
I've also tried with `python3 -m quark`, but then I've got another error:
` No module named quark.__main__; 'quark' is a package and cannot be directly executed`

**Comment by woggioni** [comment]
I'm pretty confident that it should work on OSX as long as you have the right folder in `$PATH` (on linux it is `$HOME/.local/bin`, on OSX there must be an equivalent one). No idea about Windows and I don't even have the chance to try it, but I expect a similar behaviour. The fact that it doesn't work with the `-m` syntax is something that could be addressed but it is actually expected

**Comment by cvtsi2sd** [comment]
I don't think that the pip package has been broken explicitly, but ATM pretty much nobody uses it, as it is generally more inconvenient to install, upgrade and test changes on.

The specific error is something that I've seen indeed on machines where the path where `pip` installs executables isn't in the PATH - something I've seen even on older Linux machines, or on some "regular" Linux machines when logging in through ssh. TBH, if I were you I wouldn't even bother trying to investigate this, the whole pip/setuptools shebang is a broken mess anyway, if you can avoid it - and we can, as quark is pure Python, with no dependencies, nothing to build and a single executable entrypoint - you are way better off.

For this reason, we wrote launcher scripts for Unix/Windows under `bin` (that deal with fixing up the path when launching from any workdir), so that currently the preferred install method is "clone it wherever you like" and either:

- add the `bin` directory from the checkout to your `PATH`";
- add a symlink to `bin/quark` in a directory that is already in your `PATH`;
- launch explicitly `path_to_the_checkout/bin/quark` (which uses the correct entrypoint on Unix-like OSes, and a `.cmd` launcher script on Windows).

CI dockers/build slaves clone it as a part of the project checkout and use this last method to launch it, we developers usually use one of the other two (personally I use the second one).

**Comment by woggioni** [comment]
I've just tried the pip packaging on linux and it seems to work flawlessy (except for the fact that launching `quark co` doesn't do anything, doesn't print anything and just returns 0, really small thing but still probably not the expected behaviour)

**Comment by woggioni** [comment]
> I don't think that the pip package has been broken explicitly, but ATM pretty much nobody uses it, as it is generally more inconvenient to install, upgrade and test changes on.
> 
> The specific error is something that I've seen indeed on machines where the path where `pip` installs executables isn't in the PATH - something I've seen even on older Linux machines, or on some "regular" Linux machines when logging in through ssh. TBH, if I were you I wouldn't even bother trying to investigate this, the whole pip/setuptools shebang is a broken mess anyway, if you can avoid it - and we can, as quark is pure Python, with no dependencies, nothing to build and a single executable entrypoint - you are way better off.
> 
> For this reason, we wrote launcher scripts for Unix/Windows under `bin` (that deal with fixing up the path when launching from any workdir), so that currently the preferred install method is "clone it wherever you like" and either:
> 
>     * add the `bin` directory from the checkout to your `PATH`";
> 
>     * add a symlink to `bin/quark` in a directory that is already in your `PATH`;
> 
>     * launch explicitly `path_to_the_checkout\bin\quark` (which uses a `/bin/sh` launcher script on Unix-like OSes, and a `.cmd` launcher script on Windows).
> 
> 
> CI dockers/build slaves clone it as a part of the project checkout and use this last method to launch it, we developers usually use one of the other two (personally I use the second one).

I prefer to install it with pip for the simple reason that it is the officially supported method for distributing and installing Python packages, even though you are mostly right in your criticism

**Comment by cvtsi2sd** [comment]
Closing, as not quark-specific - this comes from a system issue common to all pip-installed packages (for them to work the path where pip installs the binaries must be in the system PATH).
